### ISSUE TITLE
Suggestion: Option to place top result at the end

### ISSUE THREAD

**Issue by bekhor** [alfredapp/window-switcher-workflow#4]
Hi there,

I absolutely love your workflow! Thank you.

The only suggestion I have is that, in order to mimic typical cmd-tab and alt-tab behaviour, to move the top result (which is the current active window) to the bottom of the list. In this way, when I hit your workflow, I can then just hit enter to go to the previous window that was active. Currently, I have to hit down once and then enter to pull up the previous window. 

This is a subtle difference, but UX can be about the small details. And as I mentioned, your workflow would then be aligned with cmd-tab and alt-tab behaviour on Mac and Windows. 

(If you go ahead with it, I suggest that it be added as an option as people may not want this behaviour, especially if they are used to how your workflow operates currently.)

Just my two cents!

**Comment by vitorgalvao** [comment]
Thank you for the kind words and the suggestion. Adding the top window at the bottom would be confusing, though, and might not make it clear they are shown in order. An alternative would be to hide that result entirely.

However, checking the topmost focused window comes with a performance cost. So you’re saving an extra key press but having to wait longer for results to show up anyway. We can’t just outright ignore the topmost window (would be faster) since that may not be in focus (e.g. if you clicked the Desktop).

The workflow isn’t meant as a replacement to ⌘⇥ (which lists applications, not windows). If one *knows* they want the immediately previous window, the standard macOS shortcuts apply. The workflow allows you to type to filter for the window you want and is geared for use when you’re looking for something.

I have considered this option before but didn’t add it due to the above. The added complexity *and* extra slowness didn’t justify the tradeoff.
